# Generated by Django 6.0.3 on 2026-03-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rateplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sub_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_type',
            field=models.CharField(choices=[('hourly', 'Per Hour'), ('fixed', 'Fixed Price'), ('daily', 'Per Day'), ('package', 'Package'), ('emergency', 'Emergency')], default='hourly', max_length=20),
        ),
    ]
