# Generated by Django 6.0.3 on 2026-03-22 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_service_sub_category_alter_service_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='rateplan',
            name='service',
        ),
        migrations.AddField(
            model_name='rateplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='plan_for',
            field=models.CharField(choices=[('b2c', 'Individual Customer'), ('b2b', 'Corporate Client'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='plan_type',
            field=models.CharField(choices=[('hourly', 'Per Hour'), ('fixed', 'Fixed Price'), ('daily', 'Per Day'), ('package', 'Package'), ('emergency', 'Emergency'), ('contract', 'Contract')], max_length=20),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='dashboard.category')),
            ],
        ),
        migrations.AddField(
            model_name='rateplan',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.subcategory'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
